set nocompatible

syntax on
filetype off

set rtp+=~/.vim/bundle/vundle
call vundle#rc()
Bundle 'gmarik/vundle'
source ~/.vim/bundles.vim
filetype plugin indent on

set mouse=a

set encoding=utf-8
set fileencodings=utf-8

set autochdir
set autoindent
set smartindent
set cindent
set background=dark
set expandtab
set smarttab
set shiftwidth=2
set softtabstop=2
set tabstop=2
set wildignore=*.pyc
set ignorecase
set smartcase
set hlsearch
set incsearch
set shiftround
set history=1000
set undolevels=1000
set noswapfile
set nobackup
set number
set nowrap
set backspace=indent,eol,start
set hidden
set linespace=3
set visualbell
set noerrorbells
set t_Co=256
set cursorline
set background=dark

set list listchars=tab:»-,trail:·,extends:»,precedes:«

" hi whitespace cterm=underline ctermfg=black
" autocmd ColorScheme * hi whitespace cterm=underline ctermfg=black
" match whitespace /^ \+/

" shift tab
imap <S-Tab> <Esc><<i 

" w!! force save
cmap w!! w !sudo tee % >/dev/null

colorscheme solarized
